## Project information
site_name: surveyPrev
site_description: surveyPrev and the R Shiny App

## Repository
repo_name: surveyPrev_website
repo_url: https://github.com/wu-thomas/surveyPrev_website
edit_uri: ''  #disables edit button

# Custom Homepage Elements
home_cover_image: RW_map.png # This path starts at your root mkdocs directory.
home_tagline: Shadow Wizards Only
home_description: This site is an example showcase for my "mkdocs-coverpage" repository.

# Gradient Color
home_gradient_hsla: hsla(0deg,47%,55%,1) # Default Green: hsla(160deg,47%,55%,1)

theme:
  name: material
  custom_dir: overrides\landing_page
  features:
    - navigation.indexes          # Implied section 'index.md' files
    - navigation.tabs             # Static upper section tabs (exist)
    #- navigation.tabs.sticky      # Static upper section tabs (stay)
    - navigation.top
    - navigation.footer           # Add 'previous' and 'next' buttons in the footer
    - navigation.instant          # Keep navigation from reloading
    - navigation.instant.progress # Display page loading progress-bar ( > 400ms)
    - search.highlight            # Highlight all occurrences of queried string
    - search.share                # Search Query can be copied to Clipboard
    - search.suggest              # Display likeliest completion for the last queried word


nav:
  - Home: index.md
  - About: method_direct.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js