## Project information
site_name: surveyPrev
site_description: Powered by SurveyPrev and the R Shiny App

## Repository
repo_name: surveyPrev_website
repo_url: https://github.com/wu-thomas/surveyPrev_website
edit_uri: ''  #disables edit button

theme:
  name: material
  custom_dir: overrides\landing_page
  icon: # https://www.materialpalette.com/icons
    logo: material/map
  features:
    - navigation.indexes          # Implied section 'index.md' files
    - navigation.tabs             # Static upper section tabs (exist)
    #- navigation.tabs.sticky      # Static upper section tabs (stay)
    - navigation.tracking
    - navigation.expand
    # - navigation.sections
    - navigation.top
    - navigation.footer           # Add 'previous' and 'next' buttons in the footer
    - navigation.instant          # Keep navigation from reloading
    - navigation.instant.progress # Display page loading progress-bar ( > 400ms)
    - search.highlight            # Highlight all occurrences of queried string
    - search.share                # Search Query can be copied to Clipboard
    - search.suggest              # Display likeliest completion for the last queried word

nav:
  - Home: index.md
  - Getting started:
    - About the project: overview/project_overview.md
    - Instruction videos: overview/youtube.md

  - Method: 
    - Overview: method/approach_overview.md
    - Method details:
      - Direct estimates: method/method_direct.md
    - Our innovations:
      - Publications: method/publications.md
      - Software development: method/software_development.md

plugins:
  - search
  - bibtex:
      bib_file: "docs/assets/refs.bib"

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js