## Project information
site_name: SAE4Health
site_description: Powered by SurveyPrev and the R Shiny App

## Repository
repo_name: surveyPrev_website
repo_url: https://github.com/wu-thomas/surveyPrev_website
edit_uri: ''  #disables edit button

theme:
  name: material
  custom_dir: overrides\landing_page
  #icon: # https://www.materialpalette.com/icons
    #logo: material/map
  logo: 
    assets/Washington_Huskies_logo.svg
  features:
    - navigation.indexes          # Implied section 'index.md' files
    - navigation.tabs             # Static upper section tabs (exist)
    #- navigation.tabs.sticky      # Static upper section tabs (stay)
    - navigation.tracking
    - navigation.expand
    # - navigation.sections
    - navigation.top
    - navigation.footer           # Add 'previous' and 'next' buttons in the footer
    - navigation.instant          # Keep navigation from reloading
    - navigation.instant.progress # Display page loading progress-bar ( > 400ms)
    - search.highlight            # Highlight all occurrences of queried string
    - search.share                # Search Query can be copied to Clipboard
    - search.suggest              # Display likeliest completion for the last queried word

nav:
  - Home: index.md
  - Getting Started:
    - About the Project: overview/project_overview.md
    - Installation:
      - R Shiny App (General Version): overview/app_general.md
      - R Shiny App (WHO Version): overview/app_WHO.md
    - Instruction Videos: 
      - Data Preparation: overview/youtube_data_request.md
      - R Shiny App Demo: overview/youtube_app_demo.md
      - Method Learning Sessions: overview/youtube_method_lecture.md

  - Methods: 
    - Overview: method/approach_overview.md
    - Method Details:
      - Direct Estimates: method/method_direct.md
      - Area-level Model: method/method_area.md
      - Unit-level Model: method/method_unit.md
      - Analysis Plan: method/method_plan.md
    - Our innovations:
      - Publications: method/publications.md
      - Software development: method/software_development.md
  
  - Visualizations:
    - Overview: gallery/visual_overview.md
    - Maps: 
      - Point Estimate: gallery/point_estimate.md
      - Uncertainties: gallery/uncertainty_CI_CV.md
      - Exceedance Probability: gallery/exceedance_probability.md
      - Comparison Maps: gallery/map_comparisons.md
    - Ridge Plot: gallery/ridge_plot.md
    - Scatter Plot: gallery/scatter_plot.md

  - About Us:
    - STAB Group: team/STAB_group.md
    - Collaborators: team/collaborators.md

plugins:
  - search
  - bibtex:
      bib_file: "docs/assets/refs.bib"

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js