authors:
  yunhanwu:
    name: Yunhan Wu
    description: Creator
    avatar: https://github.com/wu-thomas/surveyPrev_website/blob/master/docs/team/photos/yunhan_kindof_smile.jpg?raw=true
    # avatar: ../team/photos/yunhan_kindof_smile.jpg
    url: https://github.com/wu-thomas

