authors:
  yunhanwu:
    name: Yunhan Wu
    description: Creator
    avatar: https://github.com/UW-statistics/surveyPrev_website/blob/master/docs/team/photos/yunhan_kindof_smile.jpg?raw=true
    url: https://github.com/wu-thomas

